### ISSUE TITLE
File Hose - Retrieve Page

### ISSUE THREAD

**Issue by flea89** [web3-storage/file-space#4]
## User needs (the receiver)
- How big are the files?
- Download it on my device?
- NTH - Inspect what's inside before downloading?
- NTH - Download a part of it.

## Acceptance criteria
- [x] User sees file size before downloading (if exposed by the api)
- [x] User can easily download the file to his device
- [x] User gets a compressed file when multiple files are shared

## NTH - Acceptance criteria (consider a follow up ticket)
- [ ] ~~User can add the files to their account~~ (see ticket #11)

## Notes
From the gateway spec it seems it should be possible to pass 
`format=tar&download=true` to get a tar.
From a quick try it's not working for me, but we should look into it a bit further.

Check here for an idea of the [wireframe](https://excalidraw.com/#room=793b54009dfdad66906d,hxioa8xKjIkJxXp13t4vCw)

**Comment by adamalton** [comment]
In my opinion, a key feature of this page should be that it advertises the FileSpace service to the person who is downloading the file. Otherwise we're totally missing the opportunity of using the "network affect" to spread the word about FileSpace and web3.storage.

I've made a separate PR to add that: #10.

And I've created a separate ticket for the "Add to my account" feature: #11.

I think this looks good.
